"""Chat agent submodule."""

import json
import re
from dataclasses import dataclass, field

from pydantic_ai import Agent, RunContext
from sqlalchemy import text
from sqlalchemy.orm import Session

from hr_hub.agent import LOGGER


# ---------------------------------------------------------------------------
# SQL safety — only SELECT statements are allowed
# ---------------------------------------------------------------------------
_DANGEROUS_SQL: re.Pattern[str] = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|EXEC|EXECUTE|PRAGMA|ATTACH|DETACH)\b",
    re.IGNORECASE,
)
_RESULT_LIMIT: int = 50

# ---------------------------------------------------------------------------
# DB schema injected into the system prompt so the LLM can write correct SQL
# ---------------------------------------------------------------------------
_SCHEMA_CONTEXT: str = """\
Database: SQLite.  Column aliases shown are the actual column names in the DB.

Table: employee
  EmployeeID   TEXT  PRIMARY KEY
  FirstName    TEXT  NOT NULL
  LastName     TEXT  NOT NULL
  Gender       TEXT  ('M' | 'F')
  Email        TEXT  UNIQUE NOT NULL
  ManagerEmail TEXT
  Laptop       TEXT
  Monitor      INTEGER  (0 = false, 1 = true)
  Headset      INTEGER  (0 = false, 1 = true)

Table: employee_info  [joined to employee via EmployeeID]
  EmployeeID        TEXT  PRIMARY KEY  FK → employee.EmployeeID
  Department        TEXT  NOT NULL
      allowed values: accounting, engineering, hr, IT, management,
                      marketing, product_management, r&d, sales, support
  Salary            TEXT  ('low' | 'medium' | 'high')
  ActiveProjects    INTEGER
  AvgMonthlyHours   INTEGER
  YearsAtCompany    INTEGER
  WorkAccidents     INTEGER  (0/1)
  ReceivedPromotion INTEGER  (0/1)
  LastEvaluation    REAL  [0.0 – 1.0]
  SatisfactionScore REAL  [0.0 – 1.0]
  Attrition         INTEGER  (0/1)
  AttritionRisk     REAL  [0.0 – 1.0]

Table: it_task
  TaskID        TEXT  PRIMARY KEY
  EmployeeID    TEXT  NOT NULL  FK → employee.EmployeeID
  EmployeeEmail TEXT
  Title         TEXT  NOT NULL
  Description   TEXT
  Assignee      TEXT
  DueDate       DATETIME
  Status        TEXT  ('Pending' | 'Canceled' | 'Completed')
  Metadata      TEXT  (JSON blob)

Table: ticket
  RequestID   TEXT  PRIMARY KEY
  RequestType TEXT  NOT NULL
  Status      TEXT  NOT NULL  ('Pending' | 'Canceled' | 'Completed')
  SubmittedBy TEXT  NOT NULL
  Title       TEXT  NOT NULL
  Text        TEXT  NOT NULL
  Actions     TEXT  (JSON blob)
  LLMResult   TEXT  (JSON blob, nullable)
  CreatedAt   DATETIME  NOT NULL
"""


# ---------------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------------
@dataclass
class QueryDeps:
    """Runtime dependencies injected into the query agent.

    Attributes:
        session (Session): Active SQLAlchemy read session.
        queries (list[str]): Accumulates every SQL statement passed to query_db;
            the last entry is used as the canonical ``sql_query`` in the response.
    """

    session: Session
    queries: list[str] = field(default_factory=list[str])



# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------
def query_db(ctx: RunContext[QueryDeps], sql_query: str) -> str:
    """Execute a read-only SQL SELECT query against the HR Hub database.
   
    The query must start with SELECT. Any query containing write keywords
    (INSERT, UPDATE, DELETE, DROP, …) is rejected immediately. A LIMIT clause
    is appended automatically when absent to prevent oversized result sets.

    Args:
        ctx (RunContext[QueryDeps]): Execution context carrying the DB session
            and the query-history list.
        sql_query (str): A SQL SELECT statement generated by the agent.

    Returns:
        str: JSON-encoded list of result-row dicts on success, or an ``ERROR:``
            prefixed message on validation or execution failure.
    """
    stripped: str = sql_query.strip()

    if not stripped.upper().startswith("SELECT"):
        return "ERROR: Only SELECT queries are permitted."

    if _DANGEROUS_SQL.search(stripped):
        return "ERROR: Forbidden query — only SELECT queries are permitted."

    limited: str = stripped.rstrip(";")
    if "LIMIT" not in limited.upper():
        limited = f"{limited} LIMIT {_RESULT_LIMIT};"

    ctx.deps.queries.append(limited)
    LOGGER.info(f"query_db executing: {limited!r}")

    try:
        result = ctx.deps.session.execute(text(limited))
        columns = list(result.keys())
        rows = [dict(zip(columns, row)) for row in result.fetchall()]
        LOGGER.info(f"query_db returned {len(rows)} row(s)")
        return json.dumps(rows, default=str)
    except Exception as e:
        LOGGER.error(f"query_db execution error: {e}")
        return f"ERROR: Query execution failed — {e}"


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------
chat_agent: Agent[QueryDeps, str] = Agent(
    name="HR Chat Agent",
    model="groq:openai/gpt-oss-120b",
    deps_type=QueryDeps,
    output_type=str,
    retries=0,
    tools=[query_db],
    system_prompt=f"""\
You are a read-only HR data analyst with access to the HR Hub SQLite database.

Rules:
1. If the user request is not about employee data, return: `Google is your friend!`.
2. Only SELECT queries are allowed — write operations will be rejected by the tool.
3. If you cannot comply with the user request, return: `I can only answer HR questions.`
4. Use the query_db tool to fetch real data before answering. NEVER invent numbers.
5. If the query returns no rows, say so clearly and do not guess.
6. Do NOT return the query to the user, and do NOT explain how you got the results.
7. Keep the answer brief and factual. Use direct and plain language.
8. EASTER EGG: if the user asks who your worst enemy is, return: `**Izza Mario aah!**`.

{_SCHEMA_CONTEXT}
""",
)
