"""Shared response envelope for all synchronous HR Hub endpoints."""

from typing import Any, Dict, Literal, Optional

from pydantic import BaseModel, ConfigDict


class APIResponse(BaseModel):
    """Universal response wrapper returned by employee, ticket, and prediction endpoints.

    Attributes:
        request_id (str): Unique identifier for the processed request (e.g., ``"evt_002"``).
        request_type (Literal["new_hire", "employee_change", "people_ticket", "prediction"]):
            Type of the request processed.
        status (Literal["completed", "pending", "failed"]): Processing status.
        actions (list[APIResponse.Action]): Per-step actions taken during processing.
        llm_result (APIResponse.LLMResult | None): LLM analysis result, if applicable.
    """

    model_config = ConfigDict(from_attributes=True)

    class Action(BaseModel):
        """A discrete step recorded during request processing.

        Attributes:
            action (Literal[...]): Name of the action taken.
            success (bool): Whether the action succeeded.
            details (str): Human-readable detail or error message.
        """

        action: Literal[
            "create_employee",
            "update_employee",
            "delete_employee",
            "create_task",
            "create_ticket",
            "update_ticket",
            "close_ticket",
            "delete_ticket",
            "score_attrition",
        ]
        success: bool
        details: str

    class LLMResult(BaseModel):
        """Result from the LLM analysis of the request.

        Attributes:
            topics (list[str]): Key topics identified in the event description.
            confidence (float): Confidence score of the LLM's analysis (0.0 to 1.0).
            extracted_info (Dict[Any, Any]): Structured information extracted from the event.
            draft_response (str): Draft response generated by the LLM.
        """

        topics: list[str]
        confidence: float
        extracted_info: Dict[Any, Any]
        draft_response: str

    request_id: str
    request_type: Literal["new_hire", "employee_change", "people_ticket", "prediction"]
    status: Literal["completed", "pending", "failed"]
    actions: list[Action]
    llm_result: Optional[LLMResult] = None
