"""Model for the HR Hub agent output."""

from typing import Literal, Optional, Dict, Any
from pydantic import BaseModel, ConfigDict


class APIResponse(BaseModel):
    """Model for the HR Hub output.

    Attributes:
        request_id (str): Unique identifier for the processed request (e.g., "evt_002")
        request_type (Literal["new_hire", "employee_change", "ticket"]):
            Type of the request processed.
        status (Literal["completed", "pending", "failed"]):
            Processing status.
        actions (list[Action]): List of actions taken by the agent based on the request
        llm_result (LLMResult, optional): Result from the LLM analysis, if applicable
    """
    model_config = ConfigDict(from_attributes=True)

    request_id: str
    request_type: Literal["new_hire", "employee_change", "ticket"]
    status: Literal["completed", "pending", "failed"]
    actions: list[Action]
    llm_result: Optional[LLMResult] = None

    class Action(BaseModel):
        """Action taken based on the request.

        Attributes:
            action (Literal["create_employee", "update_employee", "create_task", "create_ticket", "update_ticket", "close_ticket"]):
                Description of the action taken.
            success (bool): Whether the action was successful
            details (str): Additional details about the action taken, such as error messages if it failed
        """

        action: Literal[
            "create_employee",
            "update_employee",
            "create_task",
            "create_ticket",
            "update_ticket",
            "close_ticket",
        ]
        success: bool
        details: str

    class LLMResult(BaseModel):
        """Result from the LLM analysis of the event.

        Attributes:
            topics (list[str]): Key topics identified in the event description
            confidence (float): Confidence score of the LLM's analysis (0.0 to 1.0)
            extracted_info (Dict[Any, Any]):
                Structured information extracted from the event description
            draft_response (str): A draft response generated by the LLM for the event
        """

        topics: list[str]
        confidence: float
        extracted_info: Dict[Any, Any]
        draft_response: str
