"""Model for the HR Hub agent output."""

from datetime import datetime
from typing import Literal, TypeAlias, Optional

from pydantic import BaseModel, ConfigDict


class APIResponse(BaseModel):
    """Model for the HR Hub output.

    Attributes:
        request_id (str): Unique identifier for the processed request (e.g., "evt_002")
        request_type (str): Type of the request processed (e.g., "employee_change")
        status (str): Processing status (e.g., "completed", "pending", "failed")
        actions (list[Action]): List of actions taken by the agent based on the request
        llm_result (LLMResult, optional): Result from the LLM analysis, if applicable
    """
    model_config = ConfigDict(from_attributes=True)

    request_id: str
    request_type: RequestType
    status: Status
    actions: list[Action]
    llm_result: Optional[LLMResult] = None

    class Action(BaseModel):
        """Action taken based on the request.

        Attributes:
            action (str): Description of the action taken (e.g., "Updated employee record", "Created IT ticket")
            success (bool): Whether the action was successful
            details (str): Additional details about the action taken, such as error messages if it failed
        """

        action: ActionType
        success: bool
        details: str

    class LLMResult(BaseModel):
        """Result from the LLM analysis of the event.

        Attributes:
            topics (list[str]): Key topics identified in the event description
            confidence (float): Confidence score of the LLM's analysis (0.0 to 1.0)
            extracted_info (dict): Structured information extracted from the event description
            draft_response (str): A draft response generated by the LLM for the event
        """

        topics: list[str]
        confidence: float
        extracted_info: dict
        draft_response: str


# ----- Type Aliases -----
RequestType: TypeAlias = Literal["new_hire", "employee_change", "ticket"]
Status: TypeAlias = Literal["completed", "pending", "failed"]
ActionType: TypeAlias = Literal[
    "create_employee",
    "update_employee",
    "create_task",
    "create_ticket",
    "update_ticket",
    "close_ticket",
]
