"""update_it_task_schema

Revision ID: 6331b03b6dc1
Revises: 435de9b47905
Create Date: 2026-04-15 19:52:48.727939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6331b03b6dc1'
down_revision: Union[str, Sequence[str], None] = '435de9b47905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('RequestID', sa.String(), nullable=False),
    sa.Column('RequestType', sa.String(), nullable=False),
    sa.Column('Status', sa.Enum('completed', 'pending', 'failed'), nullable=False),
    sa.Column('SubmittedBy', sa.String(), nullable=False),
    sa.Column('Subject', sa.String(), nullable=False),
    sa.Column('Text', sa.String(), nullable=False),
    sa.Column('Actions', sa.JSON(), nullable=False),
    sa.Column('LLMResult', sa.JSON(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RequestID')
    )
    op.create_index(op.f('ix_ticket_SubmittedBy'), 'ticket', ['SubmittedBy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_SubmittedBy'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
