"""base migration

Revision ID: 7bb2c7de33a2
Revises: 
Create Date: 2026-04-10 17:54:17.527981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb2c7de33a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('EmployeeID', sa.String(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('Gender', sa.Enum('M', 'F'), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('ManagerEmail', sa.String(), nullable=True),
    sa.Column('Laptop', sa.String(), nullable=True),
    sa.Column('Monitor', sa.Boolean(), nullable=True),
    sa.Column('Headset', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_index(op.f('ix_employee_Email'), 'employee', ['Email'], unique=True)
    op.create_index(op.f('ix_employee_ManagerEmail'), 'employee', ['ManagerEmail'], unique=False)
    op.create_table('employee_info',
    sa.Column('EmployeeID', sa.String(), nullable=False),
    sa.Column('Department', sa.Enum('sales', 'engineering', 'support', 'IT', 'product_management', 'marketing', 'r&d', 'accounting', 'hr', 'management'), nullable=False),
    sa.Column('Salary', sa.Enum('low', 'medium', 'high'), nullable=True),
    sa.Column('ActiveProjects', sa.SmallInteger(), nullable=True),
    sa.Column('AvgMonthlyHours', sa.SmallInteger(), nullable=True),
    sa.Column('YearsAtCompany', sa.SmallInteger(), nullable=True),
    sa.Column('WorkAccidents', sa.Boolean(), nullable=True),
    sa.Column('ReceivedPromotion', sa.Boolean(), nullable=True),
    sa.Column('LastEvaluation', sa.Float(), nullable=True),
    sa.Column('SatisfactionScore', sa.Float(), nullable=True),
    sa.Column('Attrition', sa.Boolean(), nullable=True),
    sa.Column('AttritionRisk', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employee.EmployeeID'], ),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_index(op.f('ix_employee_info_EmployeeID'), 'employee_info', ['EmployeeID'], unique=False)
    op.create_table('it_task',
    sa.Column('TaskID', sa.String(), nullable=False),
    sa.Column('EmployeeID', sa.String(), nullable=False),
    sa.Column('Title', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Assignee', sa.String(), nullable=True),
    sa.Column('DueDate', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.Enum('Pending', 'Canceled', 'Completed'), nullable=True),
    sa.Column('Metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employee.EmployeeID'], ),
    sa.PrimaryKeyConstraint('TaskID')
    )
    op.create_index(op.f('ix_it_task_EmployeeID'), 'it_task', ['EmployeeID'], unique=False)
    op.create_index(op.f('ix_it_task_TaskID'), 'it_task', ['TaskID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_it_task_TaskID'), table_name='it_task')
    op.drop_index(op.f('ix_it_task_EmployeeID'), table_name='it_task')
    op.drop_table('it_task')
    op.drop_index(op.f('ix_employee_info_EmployeeID'), table_name='employee_info')
    op.drop_table('employee_info')
    op.drop_index(op.f('ix_employee_ManagerEmail'), table_name='employee')
    op.drop_index(op.f('ix_employee_Email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
