"""update_it_task_schema

Revision ID: 9e088f42f265
Revises: 5bfc65d96b0a
Create Date: 2026-04-15 19:57:29.570211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e088f42f265'
down_revision: Union[str, Sequence[str], None] = '5bfc65d96b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_task', schema=None) as batch_op:
        batch_op.alter_column('EmployeeEmail',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_task', schema=None) as batch_op:
        batch_op.alter_column('EmployeeEmail',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
